import { Candidate, ProofOfWorkCredential } from "@/types";

export const CAMPUS_25_CANDIDATES: Candidate[] = [
  // ================= 6 JOB-READY (85% - 96%) =================
  {
    id: "cand-seed-jr-1",
    fullName: "Pooja Sundaram",
    anonymizedId: "Candidate #84A1",
    email: "pooja.sundaram@example.com",
    college: "NIT Trichy",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 NIT)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    targetRole: "Full-Stack Next.js & GraphQL Engineer",
    currentTier: "job_ready",
    readinessScore: 94,
    skills: [
      { skillId: "nextjs_rsc", skillName: "Next.js React Server Components", category: "frontend", level: "Advanced", isVerified: true, score: 96, credentialHash: "a4f89d3810c92bf2234e405e6081297e68cfb939e6a0d0a52479e0237d45f3ba" },
      { skillId: "graphql_federation", skillName: "GraphQL Apollo Federation", category: "backend", level: "Advanced", isVerified: true, score: 92, credentialHash: "b7e28f114c990a4421d09e8832a48bc7190ef2289c037fa9e1104e908efc7211" },
      { skillId: "typescript_strict", skillName: "TypeScript Strict Generics", category: "frontend", level: "Advanced", isVerified: true, score: 95 },
      { skillId: "docker_prod", skillName: "Docker Containerization", category: "devops", level: "Intermediate", isVerified: true, score: 90 },
    ],
    missingCompetencies: [],
    githubUrl: "https://github.com/poojasundaram",
    linkedinUrl: "https://linkedin.com/in/poojasundaram",
    experienceYears: 1.5,
    projects: [
      { title: "Distributed GraphQL Gateway", description: "Sub-5ms query router with Apollo Federation & Redis caching.", tech: ["GraphQL", "TypeScript", "Redis"] },
    ],
    pipelineStatus: "shortlisted",
    statusHistory: [{ status: "shortlisted", timestamp: "2026-09-22 10:15", updatedBy: "Acme Recruiter" }],
    credentials: [
      {
        hash: "a4f89d3810c92bf2234e405e6081297e68cfb939e6a0d0a52479e0237d45f3ba",
        candidateId: "cand-seed-jr-1",
        candidateName: "Pooja Sundaram",
        candidateEmail: "pooja.sundaram@example.com",
        skillId: "nextjs_rsc",
        skillName: "Next.js React Server Components",
        score: 96,
        passedQuestions: 3,
        totalQuestions: 3,
        issuedAt: "2026-09-20T11:42:00Z",
        issuerOrg: "SkillSetu Verification Engine",
        isSponsored: true,
        sponsorOrg: "Acme HyperScale Systems",
        canonicalPayload: JSON.stringify({ skill: "Next.js RSC", score: 96, integrity: "verified" }),
        answersLog: [
          {
            questionId: "q1",
            question: "How do React Server Components eliminate client-side bundle waterfall?",
            selectedOption: "Rendering on the server and streaming serialized JSON wire format to the browser.",
            isCorrect: true,
            timeSpentSeconds: 35,
          },
        ],
        antiCheatAudit: { tabBlurEvents: 0, flagged: false },
      },
    ],
  },
  {
    id: "cand-seed-jr-2",
    fullName: "Karthik Raman",
    anonymizedId: "Candidate #91B3",
    email: "karthik.raman@example.com",
    college: "IIT Madras",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 IIT)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    targetRole: "Senior FastAPI & Microservices Architect",
    currentTier: "job_ready",
    readinessScore: 92,
    skills: [
      { skillId: "fastapi_async", skillName: "FastAPI Async Concurrency", category: "backend", level: "Advanced", isVerified: true, score: 94, credentialHash: "f199b22a01948cd89e1029148bc7210ef8992a01988ef110298ecba091172a11" },
      { skillId: "redis_locks", skillName: "Redis Redlock Distributed Coordination", category: "backend", level: "Advanced", isVerified: true, score: 90, credentialHash: "c0189fa9822a1048bce98110948acba19827018abce0917281bc89a018726ba1" },
      { skillId: "postgres_opt", skillName: "PostgreSQL B-Tree Index Tuning", category: "backend", level: "Advanced", isVerified: true, score: 92 },
    ],
    missingCompetencies: [],
    githubUrl: "https://github.com/karthikraman",
    linkedinUrl: "https://linkedin.com/in/karthikraman",
    experienceYears: 1.0,
    projects: [
      { title: "High-Throughput Order Engine", description: "12,000 req/sec asynchronous matching engine in FastAPI.", tech: ["FastAPI", "Redis", "Docker"] },
    ],
    pipelineStatus: "interview",
    statusHistory: [{ status: "interview", timestamp: "2026-09-23 14:00", updatedBy: "Engineering Director" }],
    credentials: [],
  },
  {
    id: "cand-seed-jr-3",
    fullName: "Sneha Patel",
    anonymizedId: "Candidate #77C9",
    email: "sneha.patel@example.com",
    college: "BITS Pilani",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 Premier)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    targetRole: "AI/RAG Systems Engineer",
    currentTier: "job_ready",
    readinessScore: 90,
    skills: [
      { skillId: "vector_hnsw", skillName: "Vector Embeddings & HNSW Indexing", category: "data_ai", level: "Advanced", isVerified: true, score: 91, credentialHash: "e391a82bc0189aa1028741098ef91823908acb19280198bc7819028309182bac" },
      { skillId: "langchain_rag", skillName: "RAG Evaluation & Hybrid Search", category: "data_ai", level: "Advanced", isVerified: true, score: 89 },
      { skillId: "python_core", skillName: "Python Performance & Memory Profiling", category: "core", level: "Advanced", isVerified: true, score: 92 },
    ],
    missingCompetencies: [],
    githubUrl: "https://github.com/snehapatel",
    linkedinUrl: "https://linkedin.com/in/snehapatel",
    experienceYears: 1.2,
    projects: [
      { title: "Sub-100ms Multimodal Vector Search", description: "HNSW search on 2M biomedical research abstracts.", tech: ["ChromaDB", "Python", "FastAPI"] },
    ],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-21 09:30", updatedBy: "Automated Ingestion" }],
    credentials: [],
  },
  {
    id: "cand-seed-jr-4",
    fullName: "Rahul Deshmukh",
    anonymizedId: "Candidate #55D2",
    email: "rahul.deshmukh@example.com",
    college: "RVCE Bangalore",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 State Premier)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    targetRole: "Cloud DevOps & Kubernetes Engineer",
    currentTier: "job_ready",
    readinessScore: 89,
    skills: [
      { skillId: "k8s_rbac", skillName: "Kubernetes Operator & RBAC Hardening", category: "devops", level: "Advanced", isVerified: true, score: 93 },
      { skillId: "terraform_aws", skillName: "Terraform Multi-Region IaC", category: "devops", level: "Advanced", isVerified: true, score: 87 },
      { skillId: "docker_multistage", skillName: "Docker Multi-Stage Build Optimization", category: "devops", level: "Advanced", isVerified: true, score: 91 },
    ],
    missingCompetencies: [],
    githubUrl: "https://github.com/rahuldeshmukh",
    linkedinUrl: "https://linkedin.com/in/rahuldeshmukh",
    experienceYears: 1.0,
    projects: [
      { title: "Zero-Downtime EKS Blue-Green Deployer", description: "Automated ArgoCD sync pipeline with Canary traffic shifting.", tech: ["Kubernetes", "Terraform", "Go"] },
    ],
    pipelineStatus: "screened",
    statusHistory: [{ status: "screened", timestamp: "2026-09-22 16:45", updatedBy: "Senior DevOps Lead" }],
    credentials: [],
  },
  {
    id: "cand-seed-jr-5",
    fullName: "Divya Krishnan",
    anonymizedId: "Candidate #38E6",
    email: "divya.krishnan@example.com",
    college: "Anna University CEG",
    anonymizedCollege: "Verified Accredited Institution (Historic State University)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    targetRole: "Full-Stack Next.js & GraphQL Engineer",
    currentTier: "job_ready",
    readinessScore: 87,
    skills: [
      { skillId: "react_state", skillName: "React Concurrent Mode & Zustand", category: "frontend", level: "Advanced", isVerified: true, score: 88 },
      { skillId: "graphql_api", skillName: "GraphQL Apollo Client & Caching", category: "backend", level: "Advanced", isVerified: true, score: 86 },
      { skillId: "tailwind_css", skillName: "Tailwind CSS Design Systems", category: "frontend", level: "Advanced", isVerified: true, score: 90 },
    ],
    missingCompetencies: [],
    githubUrl: "https://github.com/divyakrishnan",
    linkedinUrl: "https://linkedin.com/in/divyakrishnan",
    experienceYears: 0.8,
    projects: [
      { title: "Real-time FinTech Analytics Dashboard", description: "Sub-second financial charting with WebSocket streaming.", tech: ["Next.js", "Zustand", "Tailwind"] },
    ],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-23 11:20", updatedBy: "Inbound Pipeline" }],
    credentials: [],
  },
  {
    id: "cand-seed-jr-6",
    fullName: "Ananya Sengupta",
    anonymizedId: "Candidate #21F4",
    email: "ananya.sengupta@example.com",
    college: "VIT Vellore",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 Deemed)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    targetRole: "AI/RAG Systems Engineer",
    currentTier: "job_ready",
    readinessScore: 86,
    skills: [
      { skillId: "rag_reranking", skillName: "Cohere Re-ranking & Dense Vectors", category: "data_ai", level: "Advanced", isVerified: true, score: 87 },
      { skillId: "fastapi_serving", skillName: "FastAPI High Concurrency Serving", category: "backend", level: "Advanced", isVerified: true, score: 85 },
      { skillId: "langfuse_tracing", skillName: "Langfuse Observability & Tracing", category: "data_ai", level: "Intermediate", isVerified: true, score: 88 },
    ],
    missingCompetencies: [],
    githubUrl: "https://github.com/ananyasengupta",
    linkedinUrl: "https://linkedin.com/in/ananyasengupta",
    experienceYears: 0.9,
    projects: [
      { title: "Legal Citation Extractor", description: "Automated Indian Penal Code cross-reference using hybrid vector search.", tech: ["Python", "Qdrant", "FastAPI"] },
    ],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-24 08:15", updatedBy: "Campus Drive" }],
    credentials: [],
  },

  // ================= 12 BRIDGEABLE (68% - 83%) =================
  // TARGET DEMO HERO: Aarav Sharma (Rank #8, 74% -> Elevates to Rank #1, 94%)
  {
    id: "cand-aarav-hero",
    fullName: "Aarav Sharma",
    anonymizedId: "Candidate #9F2A",
    email: "aarav.sharma@example.com",
    college: "Tier-3 Regional Engineering College",
    anonymizedCollege: "Verified Accredited Institution (Tier-3 Rural Autonomous)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    targetRole: "Senior FastAPI & Microservices Architect",
    currentTier: "bridgeable",
    readinessScore: 74,
    skills: [
      { skillId: "python_async", skillName: "Python Async & Type Hints", category: "backend", level: "Advanced", isVerified: true, score: 95 },
      { skillId: "postgres_opt", skillName: "PostgreSQL Index Tuning", category: "backend", level: "Advanced", isVerified: true, score: 88 },
      { skillId: "docker_prod", skillName: "Docker Production Packaging", category: "devops", level: "Beginner", isVerified: false, score: 32 },
      { skillId: "fastapi_deadlock", skillName: "FastAPI Async Concurrency", category: "backend", level: "Beginner", isVerified: false, score: 45 },
    ],
    missingCompetencies: ["Docker Production Packaging", "FastAPI Async Deadlock Fix"],
    githubUrl: "https://github.com/aaravsharma-dev",
    linkedinUrl: "https://linkedin.com/in/aaravsharma-dev",
    experienceYears: 0.5,
    projects: [
      { title: "High-Volume Microservice Prototype", description: "FastAPI REST API with PostgreSQL connection pooling.", tech: ["Python", "FastAPI", "PostgreSQL"] },
    ],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-24 10:00", updatedBy: "Campus TPO Portal" }],
    credentials: [],
  },
  {
    id: "cand-1",
    fullName: "Aditya Verma",
    anonymizedId: "Candidate #4C1B",
    email: "aditya.verma@example.com",
    college: "Indian Institute of Information Technology (IIIT)",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 IIIT)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    targetRole: "Senior FastAPI & Microservices Architect",
    currentTier: "bridgeable",
    readinessScore: 78,
    skills: [
      { skillId: "react_rsc", skillName: "React Server Components", category: "frontend", level: "Advanced", isVerified: true, score: 92 },
      { skillId: "fastapi_core", skillName: "FastAPI Clean Architecture", category: "backend", level: "Intermediate", isVerified: true, score: 81 },
      { skillId: "redis_locks", skillName: "Redis Distributed Locks", category: "backend", level: "Beginner", isVerified: false, score: 38 },
    ],
    missingCompetencies: ["Redis Distributed Locks"],
    githubUrl: "https://github.com/adityaverma",
    linkedinUrl: "https://linkedin.com/in/adityaverma",
    experienceYears: 1.0,
    projects: [{ title: "SkillSetu Core Prototype", description: "Cryptographic hash generation and verifiable skills platform.", tech: ["Next.js", "FastAPI"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-20 12:00", updatedBy: "Direct Application" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-3",
    fullName: "Rohan Mehta",
    anonymizedId: "Candidate #8E2D",
    email: "rohan.mehta@example.com",
    college: "PSG Tech Coimbatore",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 State Autonomous)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    targetRole: "Cloud DevOps & Kubernetes Engineer",
    currentTier: "bridgeable",
    readinessScore: 81,
    skills: [
      { skillId: "docker_compose", skillName: "Docker Multi-Stage & Compose", category: "devops", level: "Advanced", isVerified: true, score: 89 },
      { skillId: "terraform_iac", skillName: "Terraform AWS Modules", category: "devops", level: "Intermediate", isVerified: true, score: 82 },
      { skillId: "k8s_rbac", skillName: "Kubernetes RBAC", category: "devops", level: "Beginner", isVerified: false, score: 41 },
    ],
    missingCompetencies: ["Kubernetes RBAC"],
    githubUrl: "https://github.com/rohanmehta",
    linkedinUrl: "https://linkedin.com/in/rohanmehta",
    experienceYears: 0.8,
    projects: [{ title: "Automated CI/CD with GitHub Actions", description: "Matrix test runners and auto-deploy to AWS ECS.", tech: ["Docker", "GitHub Actions"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-22 15:30", updatedBy: "University Pool" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-4",
    fullName: "Meera Nair",
    anonymizedId: "Candidate #7B3E",
    email: "meera.nair@example.com",
    college: "SRM KTR",
    anonymizedCollege: "Verified Accredited Institution (Tier-2 Deemed)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    targetRole: "AI/RAG Systems Engineer",
    currentTier: "bridgeable",
    readinessScore: 79,
    skills: [
      { skillId: "python_data", skillName: "Python NumPy & Pandas Optimization", category: "data_ai", level: "Advanced", isVerified: true, score: 91 },
      { skillId: "langchain_core", skillName: "LangChain Chains & Prompts", category: "data_ai", level: "Intermediate", isVerified: true, score: 80 },
      { skillId: "vector_hnsw", skillName: "Vector HNSW Indexing", category: "data_ai", level: "Beginner", isVerified: false, score: 44 },
    ],
    missingCompetencies: ["Vector HNSW Indexing"],
    githubUrl: "https://github.com/meeranair",
    linkedinUrl: "https://linkedin.com/in/meeranair",
    experienceYears: 0.7,
    projects: [{ title: "Customer Support RAG Agent", description: "Context-aware conversational agent with vector search.", tech: ["Python", "FastAPI", "ChromaDB"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-23 09:10", updatedBy: "Recruiter Radar" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-5",
    fullName: "Vikram Iyer",
    anonymizedId: "Candidate #6D4A",
    email: "vikram.iyer@example.com",
    college: "BITS Pilani",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 Premier)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
    targetRole: "Senior FastAPI & Microservices Architect",
    currentTier: "bridgeable",
    readinessScore: 82,
    skills: [
      { skillId: "fastapi_rest", skillName: "FastAPI Pydantic V2 Architecture", category: "backend", level: "Advanced", isVerified: true, score: 93 },
      { skillId: "postgres_acid", skillName: "PostgreSQL Isolation Levels", category: "backend", level: "Advanced", isVerified: true, score: 87 },
      { skillId: "docker_prod", skillName: "Docker Multi-Stage Build Optimization", category: "devops", level: "Beginner", isVerified: false, score: 48 },
    ],
    missingCompetencies: ["Docker Multi-Stage"],
    githubUrl: "https://github.com/vikramiyer",
    linkedinUrl: "https://linkedin.com/in/vikramiyer",
    experienceYears: 1.1,
    projects: [{ title: "Distributed Task Queue", description: "Background queue with priority retry logic.", tech: ["Python", "RabbitMQ"] }],
    pipelineStatus: "screened",
    statusHistory: [{ status: "screened", timestamp: "2026-09-23 18:20", updatedBy: "Hiring Manager" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-6",
    fullName: "Tanvi Rao",
    anonymizedId: "Candidate #5A1F",
    email: "tanvi.rao@example.com",
    college: "RVCE Bangalore",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 State Premier)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    targetRole: "Full-Stack Next.js & GraphQL Engineer",
    currentTier: "bridgeable",
    readinessScore: 76,
    skills: [
      { skillId: "nextjs_app_router", skillName: "Next.js 15 App Router", category: "frontend", level: "Advanced", isVerified: true, score: 88 },
      { skillId: "typescript_core", skillName: "TypeScript Types & Interfaces", category: "frontend", level: "Intermediate", isVerified: true, score: 79 },
      { skillId: "graphql_sub", skillName: "GraphQL Subscriptions & WebSockets", category: "backend", level: "Beginner", isVerified: false, score: 36 },
    ],
    missingCompetencies: ["GraphQL Subscriptions"],
    githubUrl: "https://github.com/tanvirao",
    linkedinUrl: "https://linkedin.com/in/tanvirao",
    experienceYears: 0.6,
    projects: [{ title: "Interactive Canvas Whiteboard", description: "Collaborative drawing board with real-time sync.", tech: ["React", "TypeScript", "Canvas"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-24 11:45", updatedBy: "Career Fair Ingest" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-7",
    fullName: "Siddharth Bose",
    anonymizedId: "Candidate #4F9C",
    email: "siddharth.bose@example.com",
    college: "GCT Coimbatore",
    anonymizedCollege: "Verified Accredited Institution (Tier-2 Government)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    targetRole: "Cloud DevOps & Kubernetes Engineer",
    currentTier: "bridgeable",
    readinessScore: 73,
    skills: [
      { skillId: "linux_kernel", skillName: "Linux System Administration", category: "core", level: "Advanced", isVerified: true, score: 86 },
      { skillId: "docker_basics", skillName: "Docker Containerization", category: "devops", level: "Intermediate", isVerified: true, score: 78 },
      { skillId: "terraform_iac", skillName: "Terraform Multi-Region IaC", category: "devops", level: "Beginner", isVerified: false, score: 35 },
    ],
    missingCompetencies: ["Terraform Multi-Region IaC"],
    githubUrl: "https://github.com/siddharthbose",
    linkedinUrl: "https://linkedin.com/in/siddharthbose",
    experienceYears: 0.5,
    projects: [{ title: "Self-Hosted Observability Stack", description: "Prometheus + Grafana + Loki pipeline on bare metal.", tech: ["Linux", "Prometheus", "Grafana"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-21 17:00", updatedBy: "TPO Bulk Ingestion" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-8",
    fullName: "Kavya Nambiar",
    anonymizedId: "Candidate #3E8B",
    email: "kavya.nambiar@example.com",
    college: "Anna University CEG",
    anonymizedCollege: "Verified Accredited Institution (Historic State University)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    targetRole: "Senior FastAPI & Microservices Architect",
    currentTier: "bridgeable",
    readinessScore: 80,
    skills: [
      { skillId: "python_oop", skillName: "Python OOP & Design Patterns", category: "core", level: "Advanced", isVerified: true, score: 91 },
      { skillId: "fastapi_orm", skillName: "FastAPI SQLAlchemy Async ORM", category: "backend", level: "Intermediate", isVerified: true, score: 84 },
      { skillId: "redis_locks", skillName: "Redis Distributed Locks", category: "backend", level: "Beginner", isVerified: false, score: 42 },
    ],
    missingCompetencies: ["Redis Distributed Locks"],
    githubUrl: "https://github.com/kavyanambiar",
    linkedinUrl: "https://linkedin.com/in/kavyanambiar",
    experienceYears: 0.8,
    projects: [{ title: "E-Commerce Flash Sale Engine", description: "Inventory reservation service with optimistic locking.", tech: ["FastAPI", "SQLAlchemy", "PostgreSQL"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-22 14:15", updatedBy: "Campus Placement" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-9",
    fullName: "Arjun Reddy",
    anonymizedId: "Candidate #2B7A",
    email: "arjun.reddy@example.com",
    college: "Tier-3 Regional Engineering College",
    anonymizedCollege: "Verified Accredited Institution (Tier-3 Rural Autonomous)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    targetRole: "Cloud DevOps & Kubernetes Engineer",
    currentTier: "bridgeable",
    readinessScore: 71,
    skills: [
      { skillId: "bash_scripting", skillName: "Bash Shell Scripting & Automation", category: "core", level: "Advanced", isVerified: true, score: 88 },
      { skillId: "docker_basics", skillName: "Docker Containerization", category: "devops", level: "Intermediate", isVerified: true, score: 76 },
      { skillId: "k8s_ingress", skillName: "Kubernetes Ingress & TLS Cert-Manager", category: "devops", level: "Beginner", isVerified: false, score: 30 },
    ],
    missingCompetencies: ["Kubernetes Ingress & TLS"],
    githubUrl: "https://github.com/arjunreddy",
    linkedinUrl: "https://linkedin.com/in/arjunreddy",
    experienceYears: 0.4,
    projects: [{ title: "Automated Backup Daemon", description: "Incremental encrypted database backups to S3.", tech: ["Bash", "Linux", "AWS"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-23 08:30", updatedBy: "Regional Hackathon Drive" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-10",
    fullName: "Ishita Joshi",
    anonymizedId: "Candidate #1D6E",
    email: "ishita.joshi@example.com",
    college: "VIT Vellore",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 Deemed)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    targetRole: "AI/RAG Systems Engineer",
    currentTier: "bridgeable",
    readinessScore: 75,
    skills: [
      { skillId: "prompt_eng", skillName: "Prompt Engineering & Few-Shot", category: "data_ai", level: "Advanced", isVerified: true, score: 89 },
      { skillId: "python_rest", skillName: "Python REST APIs", category: "backend", level: "Intermediate", isVerified: true, score: 80 },
      { skillId: "chunking_opt", skillName: "Semantic Chunking & Token Optimization", category: "data_ai", level: "Beginner", isVerified: false, score: 38 },
    ],
    missingCompetencies: ["Semantic Chunking & Token Optimization"],
    githubUrl: "https://github.com/ishitajoshi",
    linkedinUrl: "https://linkedin.com/in/ishitajoshi",
    experienceYears: 0.6,
    projects: [{ title: "Research Paper Summarizer", description: "Automated executive summary generator for arXiv PDFs.", tech: ["Python", "OpenAI API"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-24 07:40", updatedBy: "Direct Application" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-11",
    fullName: "Pranav Kulkarni",
    anonymizedId: "Candidate #9C5D",
    email: "pranav.kulkarni@example.com",
    college: "PSG Tech Coimbatore",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 State Autonomous)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80",
    targetRole: "Senior FastAPI & Microservices Architect",
    currentTier: "bridgeable",
    readinessScore: 77,
    skills: [
      { skillId: "python_concurrency", skillName: "Python Threading & Multi-Processing", category: "core", level: "Advanced", isVerified: true, score: 87 },
      { skillId: "sqlite_opt", skillName: "SQL Database Modeling", category: "backend", level: "Intermediate", isVerified: true, score: 81 },
      { skillId: "fastapi_async", skillName: "FastAPI Async Concurrency", category: "backend", level: "Beginner", isVerified: false, score: 40 },
    ],
    missingCompetencies: ["FastAPI Async Concurrency"],
    githubUrl: "https://github.com/pranavkulkarni",
    linkedinUrl: "https://linkedin.com/in/pranavkulkarni",
    experienceYears: 0.7,
    projects: [{ title: "Data Pipeline Scheduler", description: "Lightweight cron-based ETL processor.", tech: ["Python", "SQLite"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-23 16:10", updatedBy: "Placement Cell" }],
    credentials: [],
  },
  {
    id: "cand-seed-br-12",
    fullName: "Shreya Mukherjee",
    anonymizedId: "Candidate #8B4C",
    email: "shreya.mukherjee@example.com",
    college: "NIT Trichy",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 NIT)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    targetRole: "Full-Stack Next.js & GraphQL Engineer",
    currentTier: "bridgeable",
    readinessScore: 83,
    skills: [
      { skillId: "react_hooks", skillName: "React Custom Hooks & Perf", category: "frontend", level: "Advanced", isVerified: true, score: 92 },
      { skillId: "node_express", skillName: "Node.js REST Services", category: "backend", level: "Advanced", isVerified: true, score: 86 },
      { skillId: "web_workers", skillName: "Web Workers & Streaming", category: "frontend", level: "Beginner", isVerified: false, score: 45 },
    ],
    missingCompetencies: ["Web Workers & Streaming"],
    githubUrl: "https://github.com/shreyamukherjee",
    linkedinUrl: "https://linkedin.com/in/shreyamukherjee",
    experienceYears: 1.0,
    projects: [{ title: "Heavy In-Browser CSV Parser", description: "Off-thread data parsing without UI freezing.", tech: ["React", "TypeScript"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-22 13:50", updatedBy: "Campus Drive" }],
    credentials: [],
  },

  // ================= 7 HIGH DEFICIT (< 65%) =================
  {
    id: "cand-seed-hd-1",
    fullName: "Nikhil Chawla",
    anonymizedId: "Candidate #7A3B",
    email: "nikhil.chawla@example.com",
    college: "Tier-3 Regional Engineering College",
    anonymizedCollege: "Verified Accredited Institution (Tier-3 Rural Autonomous)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    targetRole: "Full-Stack Next.js & GraphQL Engineer",
    currentTier: "mismatch",
    readinessScore: 61,
    skills: [
      { skillId: "html_css", skillName: "HTML5 & CSS Responsive", category: "frontend", level: "Intermediate", isVerified: true, score: 75 },
      { skillId: "js_es6", skillName: "JavaScript ES6 Basics", category: "frontend", level: "Intermediate", isVerified: true, score: 70 },
    ],
    missingCompetencies: ["TypeScript Strict", "Docker Multi-Stage", "CI/CD Pipelines"],
    githubUrl: "https://github.com/nikhilchawla",
    linkedinUrl: "https://linkedin.com/in/nikhilchawla",
    experienceYears: 0.2,
    projects: [{ title: "Portfolio Website", description: "Static HTML/CSS personal website.", tech: ["HTML", "CSS"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-21 11:00", updatedBy: "Direct" }],
    credentials: [],
  },
  {
    id: "cand-seed-hd-2",
    fullName: "Harshita Roy",
    anonymizedId: "Candidate #6F2E",
    email: "harshita.roy@example.com",
    college: "SRM KTR",
    anonymizedCollege: "Verified Accredited Institution (Tier-2 Deemed)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    targetRole: "Cloud DevOps & Kubernetes Engineer",
    currentTier: "mismatch",
    readinessScore: 58,
    skills: [
      { skillId: "git_basics", skillName: "Git Version Control", category: "core", level: "Intermediate", isVerified: true, score: 78 },
      { skillId: "linux_cmd", skillName: "Linux Shell Basics", category: "core", level: "Beginner", isVerified: true, score: 62 },
    ],
    missingCompetencies: ["Linux Kernel Administration", "Kubernetes", "Docker Multi-Stage"],
    githubUrl: "https://github.com/harshitaroy",
    linkedinUrl: "https://linkedin.com/in/harshitaroy",
    experienceYears: 0.1,
    projects: [{ title: "Dev Server Setup Script", description: "Basic setup script for Ubuntu VPS.", tech: ["Bash"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-20 14:00", updatedBy: "Direct" }],
    credentials: [],
  },
  {
    id: "cand-seed-hd-3",
    fullName: "Varun Hegde",
    anonymizedId: "Candidate #5E1D",
    email: "varun.hegde@example.com",
    college: "GCT Coimbatore",
    anonymizedCollege: "Verified Accredited Institution (Tier-2 Government)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    targetRole: "AI/RAG Systems Engineer",
    currentTier: "mismatch",
    readinessScore: 54,
    skills: [
      { skillId: "python_intro", skillName: "Python Syntax & Scripting", category: "core", level: "Intermediate", isVerified: true, score: 72 },
    ],
    missingCompetencies: ["PyTorch Tensor Ops", "Vector HNSW Indexing", "LangChain Production"],
    githubUrl: "https://github.com/varunhegde",
    linkedinUrl: "https://linkedin.com/in/varunhegde",
    experienceYears: 0.2,
    projects: [{ title: "CSV Data Cleaner", description: "Pandas script to normalize dirty sensor logs.", tech: ["Python", "Pandas"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-21 16:30", updatedBy: "Direct" }],
    credentials: [],
  },
  {
    id: "cand-seed-hd-4",
    fullName: "Bhavna Das",
    anonymizedId: "Candidate #4D0C",
    email: "bhavna.das@example.com",
    college: "Tier-3 Regional Engineering College",
    anonymizedCollege: "Verified Accredited Institution (Tier-3 Rural Autonomous)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    targetRole: "Senior FastAPI & Microservices Architect",
    currentTier: "mismatch",
    readinessScore: 63,
    skills: [
      { skillId: "flask_basics", skillName: "Flask Synchronous APIs", category: "backend", level: "Intermediate", isVerified: true, score: 74 },
      { skillId: "mysql_basics", skillName: "MySQL Basic Queries", category: "backend", level: "Intermediate", isVerified: true, score: 70 },
    ],
    missingCompetencies: ["FastAPI AsyncIO Concurrency", "PostgreSQL Index Tuning", "Docker Multi-Stage"],
    githubUrl: "https://github.com/bhavnadas",
    linkedinUrl: "https://linkedin.com/in/bhavnadas",
    experienceYears: 0.3,
    projects: [{ title: "Student Attendance Portal", description: "Flask + MySQL web application.", tech: ["Flask", "MySQL"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-22 10:45", updatedBy: "Campus Portal" }],
    credentials: [],
  },
  {
    id: "cand-seed-hd-5",
    fullName: "Tejas Patil",
    anonymizedId: "Candidate #3C9B",
    email: "tejas.patil@example.com",
    college: "Tier-3 Regional Engineering College",
    anonymizedCollege: "Verified Accredited Institution (Tier-3 Rural Autonomous)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    targetRole: "Cloud DevOps & Kubernetes Engineer",
    currentTier: "mismatch",
    readinessScore: 49,
    skills: [
      { skillId: "basic_networking", skillName: "TCP/IP & DNS Fundamentals", category: "core", level: "Beginner", isVerified: true, score: 60 },
    ],
    missingCompetencies: ["Kubernetes Operator Patterns", "Docker Multi-Stage", "Helm Charts"],
    githubUrl: "https://github.com/tejaspatil",
    linkedinUrl: "https://linkedin.com/in/tejaspatil",
    experienceYears: 0.1,
    projects: [{ title: "Home Lab Router Setup", description: "Configured pfSense firewall for local network.", tech: ["Networking"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-23 12:10", updatedBy: "Direct" }],
    credentials: [],
  },
  {
    id: "cand-seed-hd-6",
    fullName: "Ritu Agarwal",
    anonymizedId: "Candidate #2B8A",
    email: "ritu.agarwal@example.com",
    college: "VIT Vellore",
    anonymizedCollege: "Verified Accredited Institution (Tier-1 Deemed)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    targetRole: "Full-Stack Next.js & GraphQL Engineer",
    currentTier: "mismatch",
    readinessScore: 56,
    skills: [
      { skillId: "cra_basics", skillName: "React Create-React-App Basics", category: "frontend", level: "Intermediate", isVerified: true, score: 71 },
      { skillId: "rest_basics", skillName: "REST API Consumption", category: "frontend", level: "Beginner", isVerified: true, score: 65 },
    ],
    missingCompetencies: ["React Server Components", "Next.js App Router", "GraphQL Schema Design"],
    githubUrl: "https://github.com/rituagarwal",
    linkedinUrl: "https://linkedin.com/in/rituagarwal",
    experienceYears: 0.3,
    projects: [{ title: "Recipe Finder App", description: "Client-side React app fetching Edamam recipe API.", tech: ["React"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-24 09:00", updatedBy: "Direct" }],
    credentials: [],
  },
  {
    id: "cand-seed-hd-7",
    fullName: "Manoj Kumar",
    anonymizedId: "Candidate #1A79",
    email: "manoj.kumar@example.com",
    college: "Anna University CEG",
    anonymizedCollege: "Verified Accredited Institution (Historic State University)",
    gradYear: 2026,
    avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
    targetRole: "AI/RAG Systems Engineer",
    currentTier: "mismatch",
    readinessScore: 52,
    skills: [
      { skillId: "jupyter_basics", skillName: "Jupyter Notebook & Data Exploration", category: "core", level: "Beginner", isVerified: true, score: 68 },
    ],
    missingCompetencies: ["Vector Embeddings & HNSW", "FastAPI Serving", "Docker Packaging"],
    githubUrl: "https://github.com/manojkumar",
    linkedinUrl: "https://linkedin.com/in/manojkumar",
    experienceYears: 0.2,
    projects: [{ title: "Iris Classification Model", description: "Scikit-learn baseline classifier in Jupyter.", tech: ["Python", "Scikit-Learn"] }],
    pipelineStatus: "applied",
    statusHistory: [{ status: "applied", timestamp: "2026-09-24 10:30", updatedBy: "Direct" }],
    credentials: [],
  },
];
